#!/bin/bash
echo "=== Simple Verification of consolidated_schema.sql ==="
echo ""
echo "Tables: $(grep -c "CREATE TABLE" consolidated_schema.sql)"
echo "Policies: $(grep -c "CREATE POLICY" consolidated_schema.sql)"
echo "Indexes: $(grep -c "CREATE INDEX" consolidated_schema.sql)"
echo "Views: $(grep -c "CREATE OR REPLACE VIEW" consolidated_schema.sql)"
echo "Triggers: $(grep -c "CREATE TRIGGER" consolidated_schema.sql)"
echo "Functions: $(grep -c "CREATE OR REPLACE FUNCTION" consolidated_schema.sql)"
echo ""
echo "✓ ENUMs: $(grep -c "CREATE TYPE" consolidated_schema.sql)"
echo "✓ Wilayas data: $(grep -c "Adrar\|El Meniaa" consolidated_schema.sql)"
echo "✓ Migrations: $(grep -c "Migration:" consolidated_schema.sql)"
echo "✓ Storage buckets: $(grep -c "storage.buckets" consolidated_schema.sql)"
echo ""
echo "Total lines: $(wc -l < consolidated_schema.sql)"
echo ""
echo "✓✓✓ Schema appears complete! ✓✓✓"
